
package com.dataaccess.numberconversion;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.3.3.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 44320FAD386DA46A43B846174BF0C787A0BEAD3EA49E327B18C4E49B709A495619D85DAA80DA2EF334333891530F32B24492F7F7645997EB21BDBF1272FE242B
//------------------------------------------------------------------------
import java.util.HashMap;
import java.util.Map;
import java.util.List;



public class TNCResponseData
{
    private HashMap< String,String> headers = new HashMap< String,String>();
    private String body;

    public HashMap< String,String> getHeaders()
    {
        return headers;
    }
    
    public String getBody()
    {
        return body;
    }

    public void setBody(String body)
    {
        this.body=body;
    }
}